spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/webflux
    username: root
    password: qwe123
  main:
    allow-bean-definition-overriding: true


auth:
  jwt:
    exp:
      access: ${ACCESS_TOKEN_EXP:3600}
      refresh: ${REFRESH_TOKEN_EXP:10000}
    secret: ${SECRET_KEY:ZmFhc3Rv}