spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/webflux
    username: root
    password: qwe123
    pool:
      initial-size: 100
      max-size: 500
      max-idle-time: 30m


auth:
  jwt:
    exp:
      access: ${ACCESS_TOKEN_EXP:3600}
      refresh: ${REFRESH_TOKEN_EXP:10000}
    secret: ${SECRET_KEY:ZmFhc3Rv}